name: gg_parse_stdout
description: Provides methods to extract pathes from command line output in a vscode compatible form.
version: 1.0.1
repository: https://github.com/inlavigo/gg_parse_stdout.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  gg_args: ^1.0.8
  gg_process: ^1.0.7
  path: ^1.8.0

dev_dependencies:
  gg_capture_print: ^1.0.3
  gg_install_gg: ^1.0.1
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0
